MVCCodigo2024/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCCodigo2024.Controllers
{
    public class DemoController : Controller
    {
        //ActionResult=>html
        public string HolaMundo()
        {
            return "<h1>Hola Mundo</h1>";
        }
        public string HolaCodigo()
        {
            return "<h1>Hola Codigo</h1>";
        }

        public string Formulario()
        {
            string simpleForm = @"
<form action='/submit' method='post'>
    <label for='name'>Name:</label><br>
    <input type='text' id='name' name='name'><br><br>
    <label for='email'>Email:</label><br>
    <input type='email' id='email' name='email'><br><br>
    <input type='submit' value='Submit'>
</form>";

            return simpleForm;
        }

        // GET: Demo
        public ActionResult Index()
        {
            Session["Mensaje"] = "SOY EL PROFESOR HUGO TORRICO";

            ViewBag.Mensaje = "Bienvenido a Codigo";
            ViewBag.FechaHora = DateTime.Now.ToLongDateString();

            if (DateTime.Now.Hour > 13)
                ViewBag.Saludo = "Buenas Tardes";
            else
                ViewBag.Saludo = "Buenas Días";



            return View();
        }

        // GET: Demo
        public ActionResult ListarPersonas()
        {
            return View();
        }

        public ActionResult Example()
        {
            return View();
        }

        public ActionResult Exercise()
        {
            return View();
        }

        public ActionResult Table()
        {
            return View();
        }
       

    }
}

MVCCodigo2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Mi Primera Clase de MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Demo Descripcion", "Index", "Demo", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Listar Personas", "ListarPersonas", "Demo", new { area = "" }, new { @class = "nav-link" })</li>


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>